version: "3"

services:
  web:
    container_name: transformer-chatbot
    build: .
    volumes:
      - .:/app
    environment:
      - MODEL_NAME=abeja/gpt-neox-japanese-2.7b
    ports:
      - "3000:5000"
    tty: true
